spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.99.100:32768/system?characterEncoding=UTF-8&useSSL=false
  redis:
    host: eureka-zuul
  rabbitmq:
    host: eureka-zuul
    username: root
    password: root
server:
  port: 8701
mybatis:
  type-aliases-package: com.galaxy.framework.aquarius.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      galaxy:
        framework:
          aquarius:
            mapper: debug
