spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/system?characterEncoding=UTF-8&useSSL=true
  redis:
    host: eureka-zuul
  rabbitmq:
    host: eureka-zuul
    username: root
    password: root
server:
  port: 8701
eureka:
  client:
    service-url:
      defaultZone: http://eureka-zuul:8101/eureka/
mybatis:
  type-aliases-package: com.galaxy.framework.aquarius.entity
  mapper-locations: classpath:mappers/*.xml