spring:
  application:
    name: libra
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://eureka-zuul:3306/activiti?characterEncoding=UTF-8
  redis:
    host: eureka-zuul
server:
  port: 8501
eureka:
  client:
    service-url:
      defaultZone: http://eureka-zuul:8101/eureka/